# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=250)),
                ('razon_social', models.CharField(max_length=250)),
                ('nombre_contacto', models.CharField(max_length=50)),
                ('posicion_empresa', models.CharField(max_length=50)),
                ('numero_tel', models.IntegerField()),
                ('telfono_movil', models.IntegerField()),
                ('tiempo_operacion', models.IntegerField()),
                ('productos_servicio', models.TextField()),
            ],
        ),
    ]
