# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0002_informacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema_control', models.CharField(max_length=1)),
                ('compara_planeado', models.CharField(max_length=1)),
                ('uso_indicadores', models.CharField(max_length=1)),
                ('monitoreo_indicadores', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximo_compromiso', models.CharField(max_length=1)),
                ('clima_laboral', models.CharField(max_length=1)),
                ('motivacion_empleados', models.CharField(max_length=1)),
                ('decisiones_unilaterales', models.CharField(max_length=1)),
                ('decisiones_consenso', models.CharField(max_length=1)),
                ('define_acciones', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organigrama', models.CharField(max_length=1)),
                ('procesos_documentados', models.CharField(max_length=1)),
                ('evalua_procesos', models.CharField(max_length=1)),
                ('automatiza_procesos', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Planeacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elabora_planes', models.CharField(max_length=50)),
                ('tiempo_planeacion', models.CharField(max_length=50)),
                ('participacion_empleados', models.CharField(max_length=1)),
                ('conocen_objetivos', models.CharField(max_length=1)),
                ('estartegias_plan_accion', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrata_directamente', models.CharField(max_length=1)),
                ('comibina_contratacion', models.CharField(max_length=1)),
                ('procesos_seleccion', models.CharField(max_length=1)),
                ('numero_empleados', models.IntegerField()),
                ('empleados_suficientes', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Situacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=150)),
                ('planes_largo_p', models.CharField(max_length=250)),
                ('mision', models.CharField(max_length=1)),
                ('vision', models.CharField(max_length=1)),
                ('objetivos', models.CharField(max_length=1)),
                ('estrategias', models.CharField(max_length=1)),
                ('plan_accion', models.CharField(max_length=1)),
                ('establece_valores', models.TextField()),
                ('objetivos_largo_p', models.TextField()),
                ('recursos', models.TextField()),
                ('debilidades', models.TextField()),
                ('oportunidades', models.TextField()),
                ('ventaja_empresa', models.TextField()),
                ('ventaja_competencia', models.TextField()),
            ],
        ),
    ]
