# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0003_control_direccion_organizacion_planeacion_recurso_situacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico_emp',
            name='id_control',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mincit.Control'),
        ),
        migrations.AlterField(
            model_name='diagnostico_emp',
            name='id_direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mincit.Direccion'),
        ),
        migrations.AlterField(
            model_name='diagnostico_emp',
            name='id_informacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mincit.Informacion'),
        ),
        migrations.AlterField(
            model_name='diagnostico_emp',
            name='id_organizacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mincit.Organizacion'),
        ),
        migrations.AlterField(
            model_name='diagnostico_emp',
            name='id_planeacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mincit.Planeacion'),
        ),
        migrations.AlterField(
            model_name='diagnostico_emp',
            name='id_recursos',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mincit.Recurso'),
        ),
        migrations.AlterField(
            model_name='diagnostico_emp',
            name='id_situacion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mincit.Situacion'),
        ),
    ]
