# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-24 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0004_auto_20161023_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, unique=True)),
                ('nit', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
