# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0005_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostico_emp',
            name='asesor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='diagnostico_emp',
            name='id_empresa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mincit.Empresa'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='posicion_empresa',
            field=models.CharField(choices=[('representante_legal', 'Representante Legal'), ('socio', 'Socio'), ('otro', 'Otro')], default='No seleccion', max_length=50),
        ),
    ]
