# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0008_auto_20161101_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnostico_Emp',
            new_name='DiagnosticoEmpresa',
        ),
    ]
