# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0010_auto_20161105_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='id_informacion',
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='nombre_empresa',
        ),
        migrations.AddField(
            model_name='informacion',
            name='id_empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mincit.Empresa'),
        ),
    ]
