# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0011_auto_20161105_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_aspectos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_financiera',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_internacionalizacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_mercadeo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_produccion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_resumen',
            field=models.IntegerField(default=0),
        ),
    ]
