# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0013_auto_20161109_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacion',
            name='estrategias',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='mision',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='objetivos',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='plan_accion',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='situacion',
            name='vision',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=20),
        ),
    ]
