# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0014_auto_20161109_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='numero_consecutivo',
            field=models.CharField(max_length=50),
        ),
    ]
