# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mincit', '0016_auto_20161210_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='establece_recompensa',
            field=models.CharField(
                choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'),
                         ('no', 'No')], default='No seleccion', max_length=20),
        ),
    ]
