# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 12:14
from __future__ import unicode_literals

from django.db import migrations, models



class Migration(migrations.Migration):
    dependencies = [
        ('mincit', '0017_recurso_establece_recompensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('sistema_contabilidad',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('contabilidad_al_dia', models.CharField(
                    choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'),
                             ('no', 'No')], default='No seleccion',
                    max_length=20)),
                ('normas_contabilidad',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('facturado_ultimo', models.IntegerField()),
                ('planificacion_financiera',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('margen_rentabilidad',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('rentabilidad_positivo',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('nivel_endeudamiento', models.CharField(
                    choices=[('alto', 'Alto'), ('medio', 'Medio'),
                             ('bajo', 'Bajo'), ('no conoce', 'No lo conoce')],
                    default='No seleccion', max_length=20)),
                ('ingresos_cumplen',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('suficiente_capital',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('flujo_caja',
                 models.CharField(choices=[('si', 'Si'), ('no', 'No')],
                                  default='No seleccion', max_length=20)),
                ('costo_producto_servicio', models.CharField(
                    choices=[('si', 'Si'), ('parcialmente', 'Parcialmente'),
                             ('no', 'No')], default='No seleccion',
                    max_length=20)),
                ('presupuesto', models.CharField(
                    choices=[('si', 'Si'), ('parcialmente', 'Parcialmente'),
                             ('no', 'No')], default='No seleccion',
                    max_length=20)),
                ('toma_decisiones', models.CharField(
                    choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'),
                             ('no', 'No')], default='No seleccion',
                    max_length=20)),
            ]
        ),
    ]
