# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0018_auto_20161214_1214'),
    ]

    operations = [
    ]
