# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mincit', '0019_auto_20161214_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='situacion',
            name='establece_valores',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')],
                                   default='No seleccion', max_length=20),
        ),
    ]
