# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0020_auto_20161214_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planeacion',
            name='conocen_objetivos',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=1),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='estartegias_plan_accion',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=1),
        ),
        migrations.AlterField(
            model_name='planeacion',
            name='participacion_empleados',
            field=models.CharField(choices=[('1', 'Si'), ('0', 'No')], default='No seleccion', max_length=1),
        ),
    ]
