# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0021_auto_20161214_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='AspectosAdicionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AspectosMejorarDiagnosticoEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspecto_mejorar', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Internacionalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paises_exportado_importado', models.TextField()),
                ('mercados_exportado_importado', models.TextField()),
                ('metas_relacion', models.TextField()),
                ('estrategia_marketing', models.TextField()),
                ('total_ventas_esperadas', models.TextField()),
                ('margen_comercial', models.TextField()),
                ('capital_presupuestado', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mercadeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('existe_departamento_mercadeo', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('mensaje_claro', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('dedica_marketing_difusion', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('delega', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('plan_mercadeo', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('implementa_plan', models.CharField(choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('tiene_cronograma', models.CharField(choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('definir_perfil', models.CharField(choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('clientes_activos_potenciales', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('paginas_web', models.CharField(choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'), ('no', 'No'), ('no tiene web', 'No Tiene Web')], default='No seleccion', max_length=20)),
                ('usar_tecnologias', models.CharField(choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'), ('no', 'No')], default='No seleccion', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlanAccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero_consecutivo', models.CharField(max_length=50)),
                ('asesor', models.CharField(max_length=100)),
                ('id_aspecto_mejora_diagnostico_empresa', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mincit.AspectosMejorarDiagnosticoEmpresa')),
            ],
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_capacidad', models.CharField(max_length=250)),
                ('normas_tecnicas', models.CharField(max_length=250)),
                ('estado_maquinaria', models.CharField(choices=[('excelente', 'Excelente'), ('muy_buena', 'Muy Buena'), ('buena', 'Buena'), ('regular', 'Regular'), ('obsoleta', 'Obsoleta')], default='No seleccion', max_length=20)),
                ('programa_produccion', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('produccion_responde', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('proceso_produccion_define', models.CharField(choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('control_calidad', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('problemas_abastecimiento', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('planea_adquisicion', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('planes_contingencia', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('realiza_inventarios', models.CharField(choices=[('si', 'Si'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('seguimiento_inventario', models.CharField(choices=[('si', 'Si'), ('parcialmente', 'Parcialmente'), ('no', 'No')], default='No seleccion', max_length=20)),
                ('eficiencia_distribucion', models.CharField(choices=[('si', 'Si'), ('parcialmente', 'Parcialmente'), ('no', 'No')], default='No seleccion', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PuntosPorDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punto_problematico', models.CharField(max_length=250)),
            ],
        ),
    ]
