# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0022_auto_20161216_0821'),
    ]

    operations = [

        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_aspectos',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to='mincit.AspectosAdicionales'),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_financiera',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to='mincit.Financiera'),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_internacionalizacion',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to='mincit.Internacionalizacion'),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_produccion',
            field=models.OneToOneField(blank=True, null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to='mincit.Produccion'),
        ),
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_resumen',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='control',
            name='compara_planeado',
            field=models.CharField(
                choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'),
                         ('no', 'No')], default='No seleccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='control',
            name='monitoreo_indicadores',
            field=models.CharField(
                choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'),
                         ('no', 'No')], default='No seleccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='control',
            name='sistema_control',
            field=models.CharField(
                choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'),
                         ('no', 'No')], default='No seleccion', max_length=20),
        ),
        migrations.AlterField(
            model_name='control',
            name='uso_indicadores',
            field=models.CharField(
                choices=[('si', 'Si'), ('mas o menos', 'Mas o Menos'),
                         ('no', 'No')], default='No seleccion', max_length=20),
        ),
    ]
