# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0023_situacion_obstaculos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_resumen',
            field=models.IntegerField(blank=True),
        ),
    ]
