# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mincit', '0025_auto_20161216_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticoempresa',
            name='id_mercadeo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mincit.Mercadeo'),
        ),
    ]
