from django.conf.urls import url

from mincit import views

app_name = 'mincit'

urlpatterns = [
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^index/$', views.InicioListViews.as_view(), name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^diagnostico_emp/(\d+)/$',
        views.DiagnosticoEmpresaListViews.as_view(),
        name='diagnostico_emp'),
    url(r'^diagnostico_emp/(\d+)/crear/$',
        views.DiagnosticoEmpresaCreateViews.as_view(),
        name='diagnostico_empresa_crear'),
    url(r'^diagnostico_emp/editar/(?P<id_diagnostico>\d+)/$',
        views.DiagnosticoEmpresaUpdateViews.as_view(),
        name='editar_diagnostico'),
    url(r'^diagnostico_emp/informacion/(\d+)/$',
        views.InformacionViews.as_view(),
        name='informacion'),
    url(r'^diagnostico_emp/informacion/crear/(\d+)/$',
        views.InformacionCreateViews.as_view(),
        name='crear_informacion'),
    url(r'^diagnostico_emp/informacion/editar/(?P<id_informacion>\d+)/$',
        views.InformacionUpdateViews.as_view(),
        name='editar_informacion'),
    url(r'^diagnostico_emp/situacion/(?P<id_diagnostico>\d+)/$',
        views.SituacionViews.as_view(),
        name='situacion'),
    url(r'^diagnostico_emp/situacion/crear/(?P<id_diagnostico>\d+)/$',
        views.SituacionCreateViews.as_view(),
        name='crear_situacion'),
    url(r'^diagnostico_emp/situacion/editar/(?P<id_situacion>\d+)/$',
        views.SituacionUpdateViews.as_view(),
        name='editar_situacion'),
    url(r'^diagnostico_emp/planeacion/(?P<id_diagnostico>\d+)/$',
        views.PlaneacionViews.as_view(),
        name='planeacion'),
    url(r'^diagnostico_emp/planeacion/crear/(?P<id_diagnostico>\d+)/$',
        views.PlaneacionCreateViews.as_view(),
        name='crear_planeacion'),
    url(r'^diagnostico_emp/planeacion/editar/(?P<id_planeacion>\d+)/$',
        views.PlaneacionUpdateViews.as_view(),
        name='editar_planeacion'),
    url(r'^diagnostico_emp/organizacion/(?P<id_diagnostico>\d+)/$',
        views.OrganizacionViews.as_view(),
        name='organizacion'),
    url(r'^diagnostico_emp/organizacion/crear/(?P<id_diagnostico>\d+)/$',
        views.OrganizacionCreateViews.as_view(),
        name='crear_organizacion'),
    url(r'^diagnostico_emp/organizacion/editar/(?P<id_organizacion>\d+)/$',
        views.OrganizacionUpdateViews.as_view(),
        name='editar_organizacion'),
    url(r'^diagnostico_emp/direccion/(?P<id_diagnostico>\d+)/$',
        views.DireccionViews.as_view(),
        name='direccion'),
    url(r'^diagnostico_emp/direccion/crear/(?P<id_diagnostico>\d+)/$',
        views.DireccionCreateViews.as_view(),
        name='crear_direccion'),
    url(r'^diagnostico_emp/direccion/editar/(?P<id_direccion>\d+)/$',
        views.DireccionUpdateViews.as_view(),
        name='editar_direccion'),
    url(r'^diagnostico_emp/control/(?P<id_diagnostico>\d+)/$',
        views.ControlViews.as_view(),
        name='control'),
    url(r'^diagnostico_emp/control/crear/(?P<id_diagnostico>\d+)/$',
        views.ControlCreateViews.as_view(),
        name='crear_control'),
    url(r'^diagnostico_emp/control/editar/(?P<id_control>\d+)/$',
        views.ControlUpdateViews.as_view(),
        name='editar_control'),
    url(r'^diagnostico_emp/recursos/(?P<id_diagnostico>\d+)/$',
        views.RecursoViews.as_view(),
        name='recursos'),
    url(r'^diagnostico_emp/recursos/crear/(?P<id_diagnostico>\d+)/$',
        views.RecursoCreateViews.as_view(),
        name='crear_recursos'),
    url(r'^diagnostico_emp/recursos/editar/(?P<id_recurso>\d+)/$',
        views.RecursoUpdateViews.as_view(),
        name='editar_recursos'),
    url(r'^diagnostico_emp/mercadeo/(?P<id_diagnostico>\d+)/$',
        views.MercadeoViews.as_view(),
        name='mercadeo'),
    url(r'^diagnostico_emp/mercadeo/crear/(?P<id_diagnostico>\d+)/$',
        views.MercadeoCreateViews.as_view(),
        name='crear_mercadeo'),
    url(r'^diagnostico_emp/mercadeo/editar/(?P<id_mercadeo>\d+)/$',
        views.MercadeoUpdateViews.as_view(),
        name='editar_mercadeo'),
    url(r'^diagnostico_emp/financiera/(?P<id_diagnostico>\d+)/$',
        views.FinancieraViews.as_view(),
        name='financiera'),
    url(r'^diagnostico_emp/financiera/crear/(?P<id_diagnostico>\d+)/$',
        views.FinancieraCreateViews.as_view(),
        name='crear_financiera'),
    url(r'^diagnostico_emp/financiera/editar/(?P<id_financiera>\d+)/$',
        views.FinancieraUpdateViews.as_view(),
        name='editar_financiera'),
    url(r'^diagnostico_emp/produccion/(?P<id_diagnostico>\d+)/$',
        views.ProduccionViewsViews.as_view(),
        name='produccion'),
    url(r'^diagnostico_emp/produccion/crear/(?P<id_diagnostico>\d+)/$',
        views.ProduccionCreateViews.as_view(),
        name='crear_produccion'),
    url(r'^diagnostico_emp/produccion/editar/(?P<id_produccion>\d+)/$',
        views.ProduccionUpdateViews.as_view(),
        name='editar_produccion'),
    url(r'^diagnostico_emp/internacionalizacion/(?P<id_diagnostico>\d+)/$',
        views.InternacionalizacionViews.as_view(),
        name='internacionalizacion'),
    url(r'^diagnostico_emp/internacionalizacion/crear/(?P<id_diagnostico>\d+)/$',
        views.InternacionalizacionCreateViews.as_view(),
        name='crear_internacionalizacion'),
    url(r'^diagnostico_emp/internacionalizacion/editar/(?P<id_internacionalizacion>\d+)/$',
        views.InternacionalizacionUpdateViews.as_view(),
        name='editar_internacionalizacion'),


]
